COMMUNITY_VERSION=$1
COMMUNITY_AUTHORING_BUNDLE_URL=$2
COMMUNITY_DELIVERY_BUNDLE_URL=$3
ENTERPRISE_VERSION=$4
ENTERPRISE_AUTHORING_BUNDLE_URL=$5
ENTERPRISE_DELIVERY_BUNDLE_URL=$6

./gradlew clean
./gradlew buildMainImages -Ptag="${COMMUNITY_VERSION}" -PauthoringBundle="$COMMUNITY_AUTHORING_BUNDLE_URL" -PdeliveryBundle="$COMMUNITY_DELIVERY_BUNDLE_URL"
./gradlew clean
./gradlew buildMainImages -Penterprise -Pimagemagick -Ptag="${ENTERPRISE_VERSION}" -PauthoringBundle="$ENTERPRISE_AUTHORING_BUNDLE_URL" -PdeliveryBundle="$ENTERPRISE_DELIVERY_BUNDLE_URL"
